CREATE DATABASE AVUS;

\c AVUS;

CREATE TABLE Avu (
  avu_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  dni VARCHAR(30) NOT NULL,
  sexo VARCHAR(20),
  nacimiento DATE,
  nacionalidad VARCHAR(50),
  email VARCHAR(255) UNIQUE,
  telefono VARCHAR(50),
  foto_url VARCHAR(500)
);

CREATE TABLE Familiar (
  familiar_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  avu_id INTEGER NOT NULL REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100),
  numero VARCHAR(50) NOT NULL,
  principal BOOLEAN DEFAULT FALSE
);

CREATE TABLE Pastilla (
  pastilla_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  avu_id INTEGER NOT NULL REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre VARCHAR(150) NOT NULL,
  dosis VARCHAR(100),
  hora TIME
);

CREATE TABLE Turno (
  turno_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  avu_id INTEGER NOT NULL REFERENCES Avu(avu_id) ON DELETE CASCADE,
  especialidad VARCHAR(150),
  medico VARCHAR(150),
  dia DATE,
  hora TIME
);

CREATE TABLE Evento (
  evento_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  avu_id INTEGER NOT NULL REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre VARCHAR(200) NOT NULL,
  fecha DATE,
  hora TIME
);

CREATE TABLE Tutorial (
  tutorial_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT,
  video VARCHAR(500)
);

CREATE TABLE Emergencia (
  emergencia_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  avu_id INTEGER NOT NULL REFERENCES Avu(avu_id) ON DELETE CASCADE,
  contacto_principal VARCHAR(50) REFERENCES Familiar(numero) ON DELETE SET NULL
);