CREATE DATABASE AVUS;
GO

USE AVUS;
GO

CREATE TABLE Avu (
  avu_id INT IDENTITY(1,1) PRIMARY KEY,
  nombre NVARCHAR(100) NOT NULL,
  apellido NVARCHAR(100) NOT NULL,
  password_hash NVARCHAR(255) NOT NULL,
  dni NVARCHAR(30) NOT NULL UNIQUE,
  genero NVARCHAR(20) NOT NULL,
  nacimiento DATE NOT NULL,
  nacionalidad NVARCHAR(50) NOT NULL,
  email NVARCHAR(255),
  telefono NVARCHAR(50),
  foto_url NVARCHAR(500)
);
GO

CREATE TABLE Familiar (
  familiar_id INT IDENTITY(1,1) PRIMARY KEY,
  avu_id INT NOT NULL FOREIGN KEY REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre NVARCHAR(100) NOT NULL,
  apellido NVARCHAR(100),
  numero NVARCHAR(50) NOT NULL,
  principal BIT DEFAULT 0
);
GO

CREATE TABLE Pastilla (
  pastilla_id INT IDENTITY(1,1) PRIMARY KEY,
  avu_id INT NOT NULL FOREIGN KEY REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre NVARCHAR(150) NOT NULL,
  dosis NVARCHAR(100),
  hora TIME
);
GO

CREATE TABLE Turno (
  turno_id INT IDENTITY(1,1) PRIMARY KEY,
  avu_id INT NOT NULL FOREIGN KEY REFERENCES Avu(avu_id) ON DELETE CASCADE,
  especialidad NVARCHAR(150),
  medico NVARCHAR(150),
  dia DATE,
  hora TIME
);
GO

CREATE TABLE Evento (
  evento_id INT IDENTITY(1,1) PRIMARY KEY,
  avu_id INT NOT NULL FOREIGN KEY REFERENCES Avu(avu_id) ON DELETE CASCADE,
  nombre NVARCHAR(200) NOT NULL,
  fecha DATE,
  hora TIME
);
GO

CREATE TABLE Tutorial (
  tutorial_id INT IDENTITY(1,1) PRIMARY KEY,
  nombre NVARCHAR(200) NOT NULL,
  descripcion NVARCHAR(MAX),
  video NVARCHAR(500)
);
GO

CREATE TABLE Emergencia (
  emergencia_id INT IDENTITY(1,1) PRIMARY KEY,
  avu_id INT NOT NULL FOREIGN KEY REFERENCES Avu(avu_id) ON DELETE CASCADE,
  contacto_principal NVARCHAR(50)
);
GO

CREATE UNIQUE INDEX IX_Avu_Email
ON Avu (email)
WHERE email IS NOT NULL;
GO